services:
  webhook-server:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5032:5032"
    env_file:
      - .env
    #environment:
      #- SERVICE_SECRET=
      #- PW_urlSupa=
      #- PW_apikey=
      #- PW_user=
      #- PW_password=
      #- PW_host=
      #- PW_database=
      #- PW_portdb=
    volumes:
      - .:/app
    networks:
      - proxy_network
    restart: unless-stopped
networks:
  proxy_network:
    external: true
    name: proxy_network 
